!function(e){var n={};function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:r})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,n){if(1&n&&(e=t(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)t.d(r,o,function(n){return e[n]}.bind(null,o));return r},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},t.p="",t(t.s="./src/js/main.js")}({"./src/js/main.js":
/*!************************!*\
  !*** ./src/js/main.js ***!
  \************************/
/*! no exports provided */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\n/* harmony import */ var _modal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./modal */ \"./src/js/modal.js\");\n\nvar slider = new Swiper('.first-slider', {\n  loop: true,\n  centeredSlides: true,\n  slidesPerView: 1,\n  navigation: {\n    nextEl: '.swiper-button-next',\n    prevEl: '.swiper-button-prev'\n  },\n  speed: 700\n});\nvar slider2 = new Swiper('.slider-2', {\n  loop: true,\n  spaceBetween: 22,\n  centeredSlides: true,\n  slidesPerView: 1,\n  navigation: {\n    nextEl: '.swiper-button-next',\n    prevEl: '.swiper-button-prev'\n  },\n  speed: 600,\n  breakpoints: {\n    1200: {\n      slidesPerView: 4,\n      spaceBetween: 22\n    },\n    900: {\n      slidesPerView: 3,\n      spaceBetween: 22\n    },\n    767: {\n      slidesPerView: 2.5,\n      spaceBetween: 20\n    },\n    500: {\n      slidesPerView: 2\n    }\n  }\n});\nObject(_modal__WEBPACK_IMPORTED_MODULE_0__[\"default\"])();\nvar card = document.querySelector('.marriege-card');\nconsole.log(card.getBoundingClientRect().y);\n\n//# sourceURL=webpack:///./src/js/main.js?")},"./src/js/modal.js":
/*!*************************!*\
  !*** ./src/js/modal.js ***!
  \*************************/
/*! exports provided: default */function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__);\nvar modals = function modals() {\n  function bindModal(triggerSelector, modalSelector, contentSelector, closeSelector) {\n    var trigger = document.querySelectorAll(triggerSelector);\n    var modal = document.querySelector(modalSelector);\n    var content = document.querySelector(contentSelector);\n    var close = document.querySelector(closeSelector);\n    trigger.forEach(function (item) {\n      item.addEventListener('click', function (event) {\n        if (event.target) {\n          event.preventDefault();\n        }\n\n        modal.classList.add('visible');\n        document.body.style.overflow = \"hidden\";\n        content.classList.add('active');\n      });\n    });\n    close.addEventListener('click', function () {\n      modal.classList.remove('visible');\n      document.body.style.overflow = \"\";\n      content.classList.remove('active');\n    });\n    modal.addEventListener('click', function (event) {\n      if (event.target === modal) {\n        modal.classList.remove('visible');\n        document.body.style.overflow = \"\";\n        content.classList.remove('active');\n      }\n    });\n  }\n\n  bindModal('.open-btn', '.popup', '.popup__content', '.popup__close');\n};\n\n/* harmony default export */ __webpack_exports__[\"default\"] = (modals);\n\n//# sourceURL=webpack:///./src/js/modal.js?")}});
//# sourceMappingURL=main.js.map
